# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CI
env:
  SCREENER_API:${{ secrets.SCREENER_API }}
  SAUCE_USERNAME:${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY:${{ secrets.SAUCE_ACCESS_KEY }}

on:
  release:
    types: [created]
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16]
        
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-verison}}
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Installing dependencies
        run: |
          npm ci
      - name: Build the app
        run: |
          npm run build 
      - name: Run component test
        run: |
          npm run test
      - name: Start the app
        run: |
          npm start &
          npx wait-on --timeout 60000
          
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
